### ISSUE TITLE
Dockerのサポートを終了する

### ISSUE THREAD

**Issue by dino3616** [shikosai33/shikosai33-web#20]
- 誰も使ってないと思うけど一応

**Comment by dino3616** [comment]
```
❯ bun dev
$ bunx --bun astro dev
54 | 					`You can download it from ${msvcDownloadLink}`,
55 | 				{ cause: error }
56 | 			);
57 | 		}
58 |
59 | 		throw new Error(
             ^
error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
 cause: {
  "name": "ResolveMessage",
  "position": null,
  "message": "Cannot find module \"@rollup/rollup-darwin-arm64\" from \"/Users/h_shiohata/Projects/shikosai33/shikosai33-web/node_modules/rollup/dist/native.js\"",
  "level": "error",
  "specifier": "@rollup/rollup-darwin-arm64",
  "importKind": "require-call",
  "referrer": "/Users/h_shiohata/Projects/shikosai33/shikosai33-web/node_modules/rollup/dist/native.js"
}

      at requireWithFriendlyError (/Users/h_shiohata/Projects/shikosai33/shikosai33-web/node_modules/rollup/dist/native.js:59:9)
      at /Users/h_shiohata/Projects/shikosai33/shikosai33-web/node_modules/rollup/dist/native.js:68:76

error: script "dev" exited with code 1
```

この問題が解決できなさそうなので docker は使わない方向で進めたいかも
